"""SS5 — PRISM cross-check helper (export and compare).

Exports small chains (m=5) to PRISM model format and validates Python
closed-form output against expected PRISM query results.

Since PRISM may not be installed, this script has two modes:
  1. Export-only: writes .pm and .pctl files that can be run with
     `prism model.pm query.pctl -const d=<D>`.
  2. Compare mode (--prism PATH): runs PRISM and compares results.

Usage:
    python SS5_prism_cross.py                    # export only
    python SS5_prism_cross.py --prism /path/to/prism
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "code"))

from mcr.reliability import reliability
from mcr.chains import random_substochastic

SEED = 20260420_05
N_CHAINS = 5
M = 5
D_HORIZON = 20

PRISM_DIR = ROOT / "data" / "synthetic" / "prism_models"
DATA_DIR = ROOT / "data" / "synthetic"
PRISM_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)


def build_prism_model(Q: np.ndarray, R_succ: np.ndarray, R_fail: np.ndarray,
                      chain_idx: int) -> str:
    """Generate a PRISM DTMC model string for the given absorbing chain."""
    m = Q.shape[0]
    SUCC = m
    FAIL = m + 1

    lines = [
        "// Absorbing Markov chain — auto-generated by SS5_prism_cross.py",
        f"// Chain index: {chain_idx}, m={m}",
        "dtmc",
        "",
        "module chain",
        f"  s : [0..{m+1}] init 0;",
        "",
    ]
    for i in range(m):
        row_parts = []
        for j in range(m):
            if Q[i, j] > 1e-12:
                row_parts.append(f"{Q[i, j]:.8f}:(s'={j})")
        if R_succ[i] > 1e-12:
            row_parts.append(f"{R_succ[i]:.8f}:(s'={SUCC})")
        if R_fail[i] > 1e-12:
            row_parts.append(f"{R_fail[i]:.8f}:(s'={FAIL})")
        if row_parts:
            lines.append(f"  [] s={i} -> {' + '.join(row_parts)};")
    # Absorbing states loop to themselves
    lines.append(f"  [] s={SUCC} -> 1:(s'={SUCC});")
    lines.append(f"  [] s={FAIL} -> 1:(s'={FAIL});")
    lines.append("")
    lines.append("endmodule")
    lines.append("")
    lines.append(f"label \"success\" = s={SUCC};")
    return "\n".join(lines)


def build_pctl_query(d: int) -> str:
    return f'P=? [ F<={d} "success" ]'


def run_prism(prism_bin: str, model_path: Path, pctl_path: Path) -> float | None:
    try:
        result = subprocess.run(
            [prism_bin, str(model_path), str(pctl_path)],
            capture_output=True, text=True, timeout=60
        )
        for line in result.stdout.splitlines():
            if "Result:" in line:
                val_str = line.split("Result:")[-1].strip().split()[0]
                return float(val_str)
    except (subprocess.TimeoutExpired, FileNotFoundError, ValueError):
        pass
    return None


def main():
    parser = argparse.ArgumentParser(description="SS5: PRISM cross-check")
    parser.add_argument("--prism", default=None, metavar="PATH",
                        help="Path to PRISM binary (optional)")
    args = parser.parse_args()

    rng = np.random.default_rng(SEED)
    records = []

    for chain_idx in range(N_CHAINS):
        seed = int(rng.integers(0, 2 ** 32))
        chain_rng = np.random.default_rng(seed)
        Q, R_succ, R_fail = random_substochastic(
            M, rho_target=chain_rng.uniform(0.3, 0.8),
            density=chain_rng.uniform(0.4, 1.0),
            succ_rate=chain_rng.uniform(0.05, 0.35),
            rng=chain_rng,
        )
        r_cf = reliability(Q, R_succ, s0=0, d=D_HORIZON)

        # Write PRISM files
        model_str = build_prism_model(Q, R_succ, R_fail, chain_idx)
        pctl_str = build_pctl_query(D_HORIZON)
        model_path = PRISM_DIR / f"chain_{chain_idx:02d}.pm"
        pctl_path = PRISM_DIR / f"chain_{chain_idx:02d}.pctl"
        model_path.write_text(model_str)
        pctl_path.write_text(pctl_str)

        record = {
            "chain_idx": chain_idx,
            "m": M,
            "d": D_HORIZON,
            "r_closed_form": float(r_cf),
            "model_file": str(model_path.relative_to(ROOT)),
            "pctl_file": str(pctl_path.relative_to(ROOT)),
        }

        if args.prism:
            r_prism = run_prism(args.prism, model_path, pctl_path)
            record["r_prism"] = r_prism
            if r_prism is not None:
                err = abs(r_cf - r_prism)
                record["abs_error"] = float(err)
                match = "✓" if err < 1e-6 else "✗"
                print(f"  chain {chain_idx}: CF={r_cf:.8f}  PRISM={r_prism:.8f}  "
                      f"err={err:.2e}  {match}")
            else:
                print(f"  chain {chain_idx}: CF={r_cf:.8f}  PRISM=N/A")
        else:
            print(f"  chain {chain_idx}: CF={r_cf:.8f}  (PRISM not run — use --prism)")

        records.append(record)

    out_json = DATA_DIR / "SS5_summary.json"
    out_json.write_text(json.dumps(records, indent=2))
    print(f"\nPRISM model files written to {PRISM_DIR}")
    print(f"Summary written to {out_json}")
    print("[DONE] SS5 complete.")


if __name__ == "__main__":
    main()
